# Copyright 2025 Logan Magee
#
# SPDX-License-Identifier: AGPL-3.0-only

name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: graalvm/setup-graalvm@v1
        with:
          distribution: graalvm-community
          java-version: 25
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew assemble
      - run: ./gradlew assemble -Dquarkus.native.enabled=true -Dquarkus.package.jar.enabled=false
      - run: ./gradlew test
      - uses: graalvm/setup-graalvm@v1
        with:
          distribution: graalvm-community
          java-version: 24
      - run: ./gradlew dokkaGeneratePublicationHtml
