# Copyright 2025 Logan Magee
#
# SPDX-License-Identifier: AGPL-3.0-only

name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: graalvm/setup-graalvm@f744c72a42b1995d7b0cbc314bde4bace7ac1fe1 # v1.5.0
        with:
          distribution: graalvm-community
          java-version: 25
      - uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2
      - run: ./gradlew assemble
      - run: ./gradlew assemble -Dquarkus.native.enabled=true -Dquarkus.package.jar.enabled=false
      - run: ./gradlew test
      - uses: graalvm/setup-graalvm@03e8abf916fd0e281b2efe7b2da3378bb0a1d085 # v1
        with:
          distribution: graalvm-community
          java-version: 24
      - run: ./gradlew dokkaGeneratePublicationHtml
